# Generated by Django 4.2.27 on 2026-05-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_file', models.FileField(upload_to='uploads/')),
                ('workflow_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes_total', models.IntegerField(default=0)),
                ('nodes_assessed', models.IntegerField(default=0)),
                ('nodes_unassessed', models.IntegerField(default=0)),
                ('avg_ede', models.FloatField(default=0.0)),
                ('nodes_with_ede', models.IntegerField(default=0)),
                ('unnecessary_pii_total', models.IntegerField(default=0)),
                ('gdpr_concerns', models.IntegerField(default=0)),
                ('gdpr_flag', models.BooleanField(default=False)),
                ('ede_risk_level', models.CharField(default='UNKNOWN', max_length=20)),
                ('node_results', models.JSONField(default=list)),
                ('ede_error', models.TextField(blank=True, default='')),
                ('aibom_available', models.BooleanField(default=False)),
                ('aibom_findings', models.JSONField(default=list)),
                ('aibom_total_issues', models.IntegerField(default=0)),
                ('aibom_risk_level', models.CharField(default='UNKNOWN', max_length=20)),
                ('aibom_error', models.TextField(blank=True, default='')),
                ('combined_risk_score', models.CharField(default='UNKNOWN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='audit.auditjob')),
            ],
        ),
    ]
