# Generated by Django 4.2.27 on 2026-05-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Batch Audit', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_workflows', models.IntegerField(default=0)),
                ('avg_ede_across_all', models.FloatField(default=0.0)),
                ('total_gdpr_flags', models.IntegerField(default=0)),
                ('total_pii_violations', models.IntegerField(default=0)),
                ('highest_risk', models.CharField(default='UNKNOWN', max_length=20)),
                ('total_aibom_issues', models.IntegerField(default=0)),
                ('summary', models.JSONField(default=list)),
                ('jobs', models.ManyToManyField(related_name='collective_reports', to='audit.auditjob')),
            ],
        ),
    ]
