# Generated by Django 4.2.27 on 2026-05-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_collectivereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='credential_findings',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='total_credential_issues',
            field=models.IntegerField(default=0),
        ),
    ]
